In [1]:
import torch
import numpy as np
import pandas as pd

from data_processing.dataset import DriftPairDataset
from models.physical_model import physical_model

In [2]:
csv_file = '../data/nextpoint_ds/next_point_dataset.csv'


In [3]:
dataset = DriftPairDataset(csv_file)

In [4]:
init_position, final_position, init_time, context, dict_path = dataset[10]

In [5]:
init_position

tensor([[ 47.2436],
        [-59.0445]], dtype=torch.float64)

In [6]:
final_position

tensor([[ 47.2409],
        [-59.0357]], dtype=torch.float64)

In [7]:
physical_position = physical_model(init_position, init_time, dict_path)
physical_position

NameError: name 'u_drift_linear_matrix' is not defined

In [11]:
test = context[:,:,5]
test

tensor([[-0.0167, -0.0167, -0.0166,  ..., -0.0164, -0.0164, -0.0164],
        [-0.0167, -0.0166, -0.0166,  ..., -0.0164, -0.0164, -0.0164],
        [-0.0166, -0.0166, -0.0166,  ..., -0.0164, -0.0164, -0.0164],
        ...,
        [-0.0164, -0.0164, -0.0164,  ..., -0.0161, -0.0161, -0.0161],
        [-0.0164, -0.0164, -0.0164,  ..., -0.0161, -0.0161, -0.0161],
        [-0.0164, -0.0164, -0.0163,  ..., -0.0161, -0.0161, -0.0161]],
       dtype=torch.float64)

In [12]:
context.size()

torch.Size([32, 32, 8])

Draft for Dataloader + Pipeline

In [13]:
dataloader = DataLoader(dataset, batch_size=2, shuffle = True)
for (idx, batch) in enumerate(dataloader):
    # do something


NameError: name 'DataLoader' is not defined